on: 
  push:
    branches:
      - master
  pull_request:

name: Cargo check and test

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-src
      - uses: actions-rs/cargo@v1
        with:
          command: check
  
  check_formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, rust-src
    - run: cargo +nightly fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo -nightly clippy --all -- -D warnings

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly 
          components: rust-src, llvm-tools-preview
      - uses: actions-rs/install@v0.1
        with:
          crate: bootimage
          version: 0.10.3
          use-tool-cache: true
      - name: Install QEMU 
        run: |
          sudo apt update
          sudo apt install qemu-system-x86
      - uses: actions-rs/cargo@v1
        with:
          command: test